---
- name: Install and configure chrony
  hosts: all
  become: yes
  vars:
    ntp_servers:
      dc_aaa:
        - ntp-aaa
      dc_zzz:
        - ntp-zzz
  tasks:
    - name: Install chrony
      apt:
        name: chrony
        state: present
        update_cache: yes

    - name: Configure chrony
      template:
        src: chrony.conf.j2
        dest: /etc/chrony/chrony.conf
        owner: root
        group: root
        mode: 0644
      notify:
        - restart chrony

  handlers:
    - name: restart chrony
      service:
        name: chrony
        state: restarted