---
- name: Install and configure Zabbix agent2
  hosts: all
  become: yes
  vars:
    zabbix_server: "zabbix_server"
  tasks:
    - name: Add Zabbix repository
      apt_repository:
        repo: "deb http://repo.zabbix.com/zabbix/7.0/debian bullseye main"
        state: present
        filename: 'zabbix'

    - name: Import Zabbix public key
      apt_key:
        url: "https://repo.zabbix.com/zabbix-official-repo.key"
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install zabbix-agent2
      apt:
        name: zabbix-agent2
        state: present

    - name: Configure zabbix agent2
      template:
        src: zabbix_agent2.conf.j2
        dest: /etc/zabbix/zabbix_agent2.conf
        owner: root
        group: root
        mode: 0644
      notify:
        - restart zabbix-agent2

  handlers:
    - name: restart zabbix-agent2
      service:
        name: zabbix-agent2
        state: restarted